### PR TITLE
Support flake

### LINKED ISSUE #1: Flakes support
Flakes will eventually be the standard way to pin nixpkgs.

### PR DESCRIPTION
**Pull request by AkihiroSuda**
See `examples/nginx-flake/flake.nix`

Fix #1 

Thanks to @tomberek for providing hints.

### CODE REVIEW

**Comment by tomberek** [comment]
I'm getting a permission denied during build regarding etc/group

**Comment by AkihiroSuda** [comment]
@tomberek Could you open an issue with `docker info` and `docker version`?

Does `docker builder prune` help?

**Comment by AkihiroSuda** [comment]
Or, maybe you are trying to `nix build` the image without using `docker build`?

Then you need  `--option build-users-group ""`

```go
	var nixBuildCmd *exec.Cmd
	if flakeMode {
		nixBuildCmd = exec.CommandContext(ctx,
			"nix",
			"--extra-experimental-features", "nix-command",
			"--extra-experimental-features", "flakes",
			"build",
			"--option", "build-users-group", "",
			"/dockerfile",
		)
	} else {
		nixBuildCmd = exec.CommandContext(ctx, "nix-build", "--option", "build-users-group", "", fullFilename)
	}
```

**Comment by AkihiroSuda** [comment]
Opened PR https://github.com/AkihiroSuda/buildkit-nix/pull/7 for improving `nix build` compatibility

**Pull request merged**
